version: '3.8'
services:
  db:
    image: mongo:latest
    networks:
      - backend_network
    restart: always
  api:
    build: ./backend
    networks:
      - backend_network
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: always

networks:
  backend_network:
    external: false
    name: backend_network
