version: '3.8'
services:
  db:
    image: mongo:latest
    networks:
      - backend_network
    restart: always
  api:
    build: ./backend
    command: node index.js
    networks:
      - backend_network
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  backend_network:
    external: false
    name: backend_network
